/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rustandandroid_HelloWord */

#ifndef _Included_com_example_rustandandroid_HelloWord
#define _Included_com_example_rustandandroid_HelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rustandandroid_HelloWord
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_rustandandroid_HelloWord_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
